'use client';

import React, { useState } from 'react';

export default function Disclaimer() {
  const [show, setShow] = useState(false);

  return (
    <>
      <button 
        onClick={() => setShow(true)} 
        className="hover:underline transition-colors hover:text-cyan-400"
      >
        Disclaimer
      </button>

      {show && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-sm">
          <div className="bg-card border border-card-border p-8 rounded-2xl shadow-2xl max-w-2xl w-full max-h-[80vh] flex flex-col relative">
            <h2 className="text-xl font-bold text-cyan-400 mb-4 shrink-0">Legal Disclaimer</h2>
            
            <div className="flex-1 overflow-y-auto pr-4 text-text-primary text-sm leading-relaxed space-y-4">
              <p>
                <strong>ResoLogix Resource Evaluation Suite</strong> is provided as a free application for informational, educational, and demonstrative purposes only. 
              </p>
              <p>
                By accessing and using this application, you acknowledge and agree that any analyses, calculations, simulations, or reports generated by ResoLogix are strictly estimates based on the data provided and the mathematical models employed. 
              </p>
              <p>
                <strong>NO WARRANTIES:</strong> The developers, creators, and Alfazen Inc. make no warranties, expressed or implied, regarding the accuracy, completeness, reliability, or suitability of the calculations or results produced by this software. The software is provided "AS IS" without any guarantees.
              </p>
              <p>
                <strong>NO LIABILITY:</strong> In no event shall the developers, Alfazen Inc., or any affiliated parties be held liable for any direct, indirect, incidental, consequential, or special damages, including but not limited to loss of data, loss of profits, or business interruption, arising out of the use or inability to use this software, even if advised of the possibility of such damages.
              </p>
              <p>
                <strong>NOT PROFESSIONAL ADVICE:</strong> The outputs of this application do not constitute professional engineering, financial, or geological advice. Users are strictly advised to consult with certified professionals and perform independent verifications before making any financial, operational, or business decisions based on these results.
              </p>
              <p>
                By clicking "Understood" below or continuing to use this application, you accept these terms in full.
              </p>
            </div>

            <div className="flex justify-end gap-3 mt-6 shrink-0">
              <button
                onClick={() => setShow(false)}
                className="px-6 py-2.5 bg-card-border hover:bg-card-border/80 text-text-primary rounded-xl font-semibold transition-colors"
              >
                Understood
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
